//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastclasswork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities_09358_09701_09625
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_country { get; set; }
    
        public virtual Countries_09358_09701_09625 Countries_09358_09701_09625 { get; set; }
    }
}
