//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PC1
{
	private HDD hdd
	{
		get;
		set;
	}

	private RAM ram
	{
		get;
		set;
	}

	private MB mb
	{
		get;
		set;
	}

	private CPU cpu
	{
		get;
		set;
	}

	public virtual HDD HDD
	{
		get;
		set;
	}

	public virtual RAM RAM
	{
		get;
		set;
	}

	public virtual CPU CPU
	{
		get;
		set;
	}

	public virtual MB MB
	{
		get;
		set;
	}

}

