var arrCountries = new Array (

'Дания', 'Denmark',
'США', 'USA',
'Россия', 'Russia',
'Германия', 'Germany',
'Нидерланды', 'Netherlands',
'Гренландия', 'Greenland',
'Швейцария', 'Switzerland',
'Нигерия', 'Nigeria',
'Эфиопия', 'Ethiopia',
'Иран', 'Iran',
'Кирибати', 'Kiribati',
'Папуа - Новая Гвинея', 'Papua New Guinea',
'Франция', 'France',
'Канада', 'Canada',
'Пакистан', 'Pakistan',
'Йемен', 'Yemen Republic',
'Чад', 'Chad',
'Великобритания', 'United Kingdom',
'Саудовская Аравия', 'Saudi Arabia',
'Австралия', 'Australia',
'Мексика', 'Mexico',
'ОАЭ', 'United Arab Emirates',
'Египет', 'Egypt',
'Колумбия', 'Colombia',
'Венесуэла', 'Venezuela',
'Гана', 'Ghana',
'Панама', 'Panama',
'Судан', 'Sudan',
'Оман', 'Oman',
'Турция', 'Turkey',
'Алжир', 'Algeria',
'Индонезия', 'Indonesia',
'Соломоновы острова', 'Solomon Islands',
'Нигер', 'Niger',
'Марокко', 'Morocco',
'Индия', 'India',
'Либия', 'Libyan Arab Jamahiriya',
'ЮАР', 'South Africa',
'Греция', 'Greece',
'Италия', 'Italy',
'Пуэрто Рико', 'Puerto Rico',
'Япония', 'Japan',
'Французская Полинезия', 'French Polynesia',
'Гондурас', 'Honduras',
'Намибия', 'Namibia',
'Маршалловы острова', 'Marshall Islands',
'Мавритания', 'Mauritania',
'Гайана', 'Guyana',
'Острова Кука', 'Cook Islands',
'Габон', 'Gabon',
'Китай', 'China (excl. Hong Kong SAR)',
'Казахстан', 'Kazakhstan',
'Исландия', 'Iceland',
'Ирак', 'Iraq',
'Сирия', 'Syrian Arab Republic',
'Бразилия', 'Brazil',
'Филиппины', 'Philippines',
'Румыния', 'Romania',
'Испания', 'Spain',
'Суринам', 'Suriname',
'Перу', 'Peru',
'Новая Зеландия', 'New Zealand',
'Джибути', 'Djibouti',
'Малайзия', 'Malaysia',
'Норвегия', 'Norway',
'Монголия', 'Mongolia',
'Мозамбик', 'Mozambique',
'Чили', 'Chile',
'Аргентина', 'Argentina',
'Сомали', 'Somalia',
'Швеция', 'Sweden',
'Мадагаскар', 'Madagascar Island',
'Эквадор', 'Ecuador',
'Кения', 'Kenya',
'Ангола', 'Angola',
'Иордания', 'Jordan',
'Шри-Ланка', 'Sri Lanka',
'Гуам', 'Guam',
'Узбекистан', 'Uzbekistan',
'Южная Корея', 'Korea (Republic of)',
'Андорра', 'Andorra',
'Багамские острова', 'Bahamas',
'Виргинские острова', 'Virgin Islands (British)',
'Вануату', 'Vanuatu',
'Ангилья', 'Anguilla',
'Коморские острова', 'Comoros',
'Антигуа и Барбуда', 'Antigua and Barbuda',
'Бельгия', 'Belgium',
'Самоа', 'Samoa (Independent State of)',
'Боливия', 'Bolivia',
'Буркина-Фасо', 'Burkina Faso',
'Уругвай', 'Uruguay',
'Уганда', 'Uganda',
'Аруба', 'Aruba',
'Танзания', 'Tanzania (United Republic)',
'Туркменистан', 'Turkmenistan',
'Эритрея', 'Eritrea',
'Парагвай', 'Paraguay',
'Португалия', 'Portugal',
'Кипр', 'Cyprus',
'Камерун', 'Cameroon (Republic of)',
'Мьянма', 'Myanmar',
'Непал', 'Nepal',
'Афганистан', 'Afghanistan',
'Бахрейн', 'Bahrain',
'Сенегал', 'Senegal',
'Центральноафриканская Республика', 'Central African Republic',
'Азербайджан', 'Azerbaijan',
'Венгрия', 'Hungary',
'Мали', 'Mali',
'Таиланд', 'Thailand',
'Бруней-Даруссалам', 'Brunei Darussalam',
'Конго', 'Congo (Democratic Republic of)',
'Босния', 'Bosnia-Herzegovina',
'Гамбия', 'Gambia',
'Вьетнам', 'Viet Nam',
'Ирландия', 'Ireland (Republic of)',
'Куба', 'Cuba',
'Доминиканская Республика', 'Dominican Republic',
'Бангладеш', 'Bangladesh',
'Коста-Рика', 'Costa Rica',
'Гваделупа', 'Guadeloupe',
'Экваториальная Гвинея', 'Equatorial Guinea',
'Камбоджа', 'Cambodia Riel',
'Грузия', 'Georgia',
'Тимор', 'Timor Leste',
'Израиль', 'Israel',
'Ливан', 'Lebanon',
'Новая Каледония', 'New Caledonia',
'Сербия', 'Serbia',
'Белиз', 'Belize',
'Либерия', 'Liberia',
'Молдова', 'Moldova',
'Украина', 'Ukraine',
'Бермудские острова', 'Bermuda',
'Конго', 'Congo Brazzaville',
'Польша', 'Poland',
'Сейшелы', 'Seychelles Islands',
'Кыргызстан', 'Kyrgyzstan',
'Гвинея', 'Guinea Bissau',
'Македония', 'Macedonia - FYROM',
'Тунис', 'Tunisia',
'Малави', 'Malawi',
'Фиджи', 'Fiji',
'Никарагуа', 'Nicaragua',
'Кабо-Верде', 'Cape Verde (Republic of)',
'Гвинея', 'Guinea',
'Хорватия', 'Croatia',
'Нидерландские Антильские острова', 'Netherlands Antilles',
'Сьерра-Леоне', 'Sierra Leone',
'Словакия', 'Slovakia',
'Австрия', 'Austria',
'Беларусь', 'Belarus',
'Барбадос', 'Barbados',
'Чехия', 'Czech Republic',
'Зимбабве', 'Zimbabwe',
'Бурунди', 'Burundi',
'Болгария', 'Bulgaria',
'Руанда', 'Rwanda',
'Сент-Винсент и Гренадины', 'St Vincent and the Grenadines',
'Гаити', 'Haiti',
'Гватемала', 'Guatemala',
'Гренада', 'Grenada',
'Французская Гвиана', 'French Guiana',
'Гонконг', 'Hong Kong (SAR of China)',
'Тайвань', 'Taiwan',
'Замбия', 'Zambia',
'остров Рождества', 'Christmas Island',
'Кокосовые острова', 'Cocos Island',
'Бенин', 'Benin',
'Латвия', 'Latvia',
'Катар', 'Qatar',
'Доминика', 'Dominica',
'Таджикистан', 'Tajikistan',
'Майотта', 'Mayotte',
'Финляндия', 'Finland',
'Тонга', 'Tonga',
'Фарерские острова', 'Faroe Islands',
'Американское Самоа', 'American Samoa',
'Мартиника', 'Martinique',
'Ботсвана', 'Botswana',
'Тувалу', 'Tuvalu',
'Острова Уоллис и Футуна', 'Wallis and Futuna Islands',
'Мальдивы', 'Maldives Islands',
'Палестина', 'Palestinian Occ. Territories',
'Сент-Люсия', 'St. Lucia',
'Остров Святой Елены', 'St. Helena Island',
'Гибралтар', 'Gibraltar',
'Мальта', 'Malta',
'Каймановы острова', 'Cayman Islands',
'Теркс и Кайкос', 'Turks and Caicos Islands',
'Армения', 'Armenia',
'Черногория', 'Montenegro',
'Острова Соединенных Штатов', 'U.S. Minor Outlying Islands',
'Эстония', 'Estonia',
'Литва', 'Lithuania',
'Ямайка', 'Jamaica',
'Палау', 'Palau Islands',
'Микронезия', 'Micronesia',
'Кувейт', 'Kuwait',
'Того', 'Togo',
'Лесото', 'Lesotho',
'Словения', 'Slovenia',
'Люксембург', 'Luxembourg',
'Макао', 'Macao - SAR of China',
'Свазиленд', 'Swaziland',
'Маврикий', 'Mauritius Island',
'Сен-Пьер и Микелон', 'St. Pierre and Miquelon',
'Монако', 'Monaco',
'Монсеррат', 'Montserrat',
'Фоклендские острова', 'Falkland Islands',
'Науру', 'Nauru',
'Сент-Китс', 'St Kitts',
'Ниуэ', 'Niue',
'Норфолк Айленд', 'Norfolk Island',
'Бутан', 'Bhutan',
'Тринидад и Тобаго', 'Trinidad and Tobago',
'Сан-Томе', 'Sao Tome and Principe Islands',
'Северные Марианские острова', 'Northern Mariana Islands',
'Реюньон', 'Reunion Island',
'Виргинские Острова США', 'Virgin Islands US',
'Сан-Марино', 'San Marino',
'Сальвадор', 'El Salvador',
'Сингапур', 'Singapore',
'Антарктида', 'Antartica',
'Албания', 'Albania',
'Лихтенштейн', 'Liechtenstein',
'Кот д\'Ивуар', 'Cote d\'Ivoire',
'Лаос', 'Lao (People\'s Democratic Republic)',
'КНДР', 'Korea (Democratic People\'s Republic Of)',
'Токелау', 'Tokelau',
'Ватикан', 'Vatican',
'Западная Сахара', 'Western Sahara',

);